include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: false
    always_specify_types: true
    eol_at_end_of_file: true
    parameter_assignments: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: false
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: true
    use_to_and_as_if_applicable: true